---
title: "Untitled"
author: "Mladen Cucak"
date: "5/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Using 

## Introduction

Text[@rotem_relativity_1971].

## Packages
```{r libraries, message=FALSE}
list.of.packages <-
  c(
    "readxl",
    "here", #package that helps paths in different platforms
    "stringr", #string manipulations
    "reshape2", #Reshaping the data to long format, needed for plotting and model fitting
    "egg", #Plotting aids: interesting themes and putting together a number of plots
    "RColorBrewer", #Color palette
    "mgsub"

  )

new.packages <-
  list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]

#Download packages that are not already present in the library
if (length(new.packages))
  install.packages(new.packages)

packages_load <-
  lapply(list.of.packages, require, character.only = TRUE)

#Print warning if there is a problem with installing/loading some of packages
if (any(as.numeric(packages_load) == 0)) {
  warning(paste("Package/s", paste(list.of.packages[packages_load != TRUE]), "not loaded!"))
} else {
  print("All packages were successfully loaded.")
}
```

# Data

!!!!Check stadnard errors for various infection levels 

```{r}
dis_df <- read_excel(here::here("cucak", "1", "dat", "P_inf_infection_Rotem.xlsx"))
dis_df <-  
  reshape2::melt(dis_df, id.var = 1:2, variable.name = "temp", value.name = "dis_inc",factorsAsStrings = F)
dis_df$temp <- as.numeric(as.character.factor(dis_df$temp))
dis_df$wet_dur_lab <- factor(dis_df$wet_dur)
levels(dis_df$wet_dur_lab) <- paste0(levels(dis_df$wet_dur_lab), "h of s. wetness") 

dis_df$inoculum_dose <- factor(dis_df$inoculum_dose, ordered = T)
head(dis_df)
```


```{r}
ggplot(dis_df,aes(x= temp, y = dis_inc, group = inoculum_dose, colour = inoculum_dose))+
geom_point()+
geom_line()+
facet_wrap(wet_dur_lab~., ncol = 4)+
scale_color_brewer(palette="GrandBudapest")+
labs(
title = "",
x = "Temperature (°C)",
y = "Disease Incidence (grades)",
color = expression(paste("Inoculum dose ( Sporangia", "/",cm^2,")", sep="")),
caption = expression(paste(
"\nFigure 1. The effect of temperature (T, in °C), inoculum dose (Sporangia, in cm) and duration of wet period (W, in hr) on infection of potato leaves by ", "Phytopthora infestans: infection levels obtained for all treatment combinations (averaes of three replicate plants)."
)))+
theme_article()+
theme(legend.position = "top")
dis_df$wet_dur_lab <- NULL 
```
